### PR TITLE
Move some pieces around

### PR DESCRIPTION
**Pull request by rmccue**
Still working on this.

### CODE REVIEW

**Comment by jazzsequence** [comment]
is this ready to merge @rmccue ?

**Comment by rmccue** [comment]
Not ready yet; I still want to go through and change a bunch more :)

**Comment by jazzsequence** [comment]
This is looks awesome @rmccue! 😁  Does the autoloader pull in new `namespace.php` files or just new classes? If it's just classes we will need to autoload the namespaces, too. Otherwise this is fab. Eager to get it merged in. 👍

**Comment by rmccue** [comment]
> Does the autoloader pull in new `namespace.php` files or just new classes?

It's not possible to autoload namespaces, so we need to have Yeoman modify the `plugin.php` file. Took a look into [`php-parser`](https://www.npmjs.com/package/php-parser), and have something partially working there.

**Pull request merged**
